export const ORDER_EVENTS = {
  CONFIRMATION_STARTED: "CONFIRMATION_STARTED",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  ORDER_FAILED: "ORDER_FAILED",

  INVENTORY_RESERVATION_SUCCESS: "INVENTORY_RESERVATION_SUCCESS",
  INVENTORY_RESERVATION_FAILED: "INVENTORY_RESERVATION_FAILED",
  INVENTORY_RESERVATION_ERROR: "INVENTORY_RESERVATION_ERROR",

  ORDER_SCORING_SUCCESS: "ORDER_SCORING_SUCCESS",
  ORDER_SCORING_FAILED: "ORDER_SCORING_FAILED",
  ORDER_SCORING_ERROR: "ORDER_SCORING_ERROR",

  SHIPPING_QUOTE_SUCCESS: "SHIPPING_QUOTE_SUCCESS",
  SHIPPING_QUOTE_FAILED: "SHIPPING_QUOTE_FAILED",
  SHIPPING_QUOTE_ERROR: "SHIPPING_QUOTE_ERROR",
} as const;